### PR TITLE
Update Port CLI Option description and README

### PR DESCRIPTION
**Pull request by John-K**
Update the README file with new CLI options and clarify description for --port

### CODE REVIEW

**Comment by PiotrZierhoffer** [comment]
Thank you for your contribution! Before merging it, could I ask you to reword the commit messages, according to CONTRIBUTING.rst? As it relates to #73, the correct format would be:
"[#73] Add extra CLI Args from emul8 to the README."
"[#73] Clarify description of -P/--port CLI Option."
 - with number and a dot.

If you prefer I may fix it myself and merge it manually, though.

**Comment by John-K** [comment]
Format fixed as requested

**Comment by PiotrZierhoffer** [comment]
Thanks! If you need any more information on using Emul8, just let us know, either here or directly by email!

**Comment by John-K** [comment]
Will do, thanks!

**Pull request merged**
